name: Full test suite

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+(?:(?:rc|a|b)[0-9]+)?"  # all SemVer releases

jobs:

  full-test-suite:

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        py-version:
          - "3.11"
          - "3.12"

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.py-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.py-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[tests]
        pip install mypy

    - name: Unit tests with pytest
      run: |
        pytest ./tests/unit

    - name: Integration tests with pytest
      run: |
        pytest ./tests/integration
